version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    assignees:
      - EmaSuriano
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    rebase-strategy: auto
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
