version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - EmaSuriano
  ignore:
  - dependency-name: contentful-import
    versions:
    - 8.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: cypress-axe
    versions:
    - 0.12.0
